apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-secret
  namespace: kafka
type: Opaque
data:
  AUTH_TYPE: TE9HSU5fRk9STQ==
  SPRING_SECURITY_USER_NAME: azhzX2FkbWlu #k8s_admin
  SPRING_SECURITY_USER_PASSWORD: azhzQEFkbWluMTIz #k8s@Admin123
  BASE_URL: L2s4cw== #k8s