apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kafka
data:
  NODE_ENV: "development"
  APP_NAME: "RoomFinder"
  JWT_SECRET: "mySecret@jwt123" # TODO: keep in the secrets
  JWT_EXPIRES: "12h"
  JWT_HASH_ALGORITHM: "HS256"