apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  PORT: NDAwMQ==
  APP_URL: aHR0cDovL2xvY2FsaG9zdDo0MDAx
  APP_NAME: Um9vbUZpbmRlcg==
  DATABASE_URI: bW9uZ29kYjovL3VzZXItbW9uZ28tc2VydmljZToyNzAxNw==
  KAFKA_BROKER_IDS: bG9jYWxob3N0OjkwOTMsbG9jYWxob3N0OjkwOTUsbG9jYWxob3N0OjkwOTc=

