apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: comment-deployment 
  namespace: kafka
spec:
  replicas: 1 
  selector: 
    matchLabels: 
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: room-finder-comment
          image: surajthaqurie/roomfinder-commentservice
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                   name: app-config
                   key: NODE_ENV        
            - name: PORT
              valueFrom:
                secretKeyRef:
                   name: comment-service-secret
                   key: PORT        
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                   name: comment-service-secret
                   key: APP_URL        
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                   name: app-config
                   key: APP_NAME        
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                   name: db-service-secret
                   key: COMMENT_DATABASE_URL        
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                   name: comment-service-secret
                   key: KAFKA_HOST        
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                   name: app-config
                   key: JWT_SECRET        
            - name: JWT_EXPIRES
              valueFrom:
                configMapKeyRef:
                   name: app-config
                   key: JWT_EXPIRES        
            - name: JWT_HASH_ALGORITHM
              valueFrom:
                configMapKeyRef:
                   name: app-config
                   key: JWT_HASH_ALGORITHM            
        
          # Defines the ports to open in the container.
          # ports:
          #   # Indicates that the container will listen on port 4001.
          #   - containerPort: 4001
           
          # This section is used to define resource requests and limits for the container.  
          # resources:
          #   # Specifies the maximum amount of CPU and memory that the container is allowed to use.
          #   limits:
          #     memory: "256Mi" # Maximum memory allowed (256 MiB of memory)
          #     cpu: "200m" # Maximum CPU allowed (200 milliCPU ((0.2 CPU cores))
          #   # Specifies the initial amount of CPU and memory that the container requests when it starts.
          #   requests:
          #     memory: "128Mi" # Initial memory request (128 MiB of memory)
          #     cpu: "100m" # Initial CPU request (100 milliCPU (0.1 CPU cores) initially.)

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: comment
  name: comment-service
  namespace: kafka
spec:
  selector:
    app: comment
  ports:
    - name: auth
      protocol: TCP
      port: 4004
      targetPort: 4004
